### ISSUE TITLE
Add Pinterest dataset to pipeline

### ISSUE THREAD

**Issue by aaossa** [aaossa/Model-experiments#20]
Previous [notes](https://www.notion.so/Pinterest-dataset-a35ec398edc24266961d8f90a7aefb9a) from Notion.

- [X] Preprocessing (Done in #27 )
- [X] Sampling (Done in #42)
- [X] ~Training~
- [X] Results (Done in #42)

---

More:

* Embedding size causes RAM problems while reducing dimensions with PCA. An option is to use IncrementalPCA with a generous batch size.
